/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;
import javax.swing.*;
import java.sql.*;
import java.awt.*;

/**
 *
 * @author LEGION
 */
public class Beranda extends javax.swing.JFrame {
    DefaultListModel dlm = new DefaultListModel();
    JDBC conn; 
    int idKereta, hargaTiket;
    String namaKereta, gerbong, kelas, jadwalBerangkat, jadwalTiba, stasiunAsal, stasiunTujuan;
    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        conn = new JDBC();
        if(conn == null){
            JOptionPane.showMessageDialog(this, "Tidak bisa menyambungkan ke database!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etrainText = new javax.swing.JLabel();
        listKAText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKA = new javax.swing.JList<>();
        namaKeretaLabel = new javax.swing.JLabel();
        gerbongLabel = new javax.swing.JLabel();
        kelasLabel = new javax.swing.JLabel();
        berangkatLabel = new javax.swing.JLabel();
        tibaLabel = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();
        asalLabel = new javax.swing.JLabel();
        tujuanLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etrainText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etrainText.setText("E-TRAIN ");

        listKAText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listKAText.setText("LIST KERETA API");

        listKA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listKAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listKA);

        namaKeretaLabel.setText("Nama Kereta Api :  ");

        gerbongLabel.setText("Gerbong : ");

        kelasLabel.setText("Kelas : ");

        berangkatLabel.setText("Jadwal Berangkat : ");

        tibaLabel.setText("Jadwal Tiba : ");

        hargaLabel.setText("Harga Tiket : ");

        asalLabel.setText("Stasiun Asal : ");

        tujuanLabel.setText("Stasiun Tujuan : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(etrainText)
                .addGap(322, 322, 322))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listKAText)
                    .addComponent(namaKeretaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gerbongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kelasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(berangkatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tibaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(hargaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(asalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tujuanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(etrainText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listKAText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaKeretaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerbongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(berangkatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tibaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tujuanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listKAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listKAMouseClicked
        // TODO add your handling code here:
        /*
        for(int i=0; i<dlm.getSize(); i++){
            if(listKA.isSelectedIndex(i)){
                try{
                    Connection koneksi;
                    Koneksi registerKoneksi = new Koneksi();
                    koneksi = registerKoneksi.getKoneksi();
                    Statement statement = koneksi.createStatement();
                    String sql = "SELECT * FROM kereta";
                    ResultSet resultSet = statement.executeQuery(sql);
                    
                    while(resultSet.next()){
                        if(resultSet.getString("namaKereta").equals(dlm.get(i))){
                            idKereta = resultSet.getInt("idKereta");
                            
                            namaKeretaLabel.setText("Nama Kereta : " + resultSet.getString("namaKereta"));
                            namaKereta = resultSet.getString("namaKereta");
                            
                            gerbongLabel.setText("Gerbong : " + resultSet.getString("gerbong"));
                            gerbong = resultSet.getString("gerbong");
                            
                            kelasLabel.setText("Kelas : " + resultSet.getString("kelas"));
                            kelas = resultSet.getString("kelas");
                            
                            berangkatLabel.setText("Jadwal Berangkat : " + resultSet.getString("jadwalBerangkat"));
                            jadwalBerangkat = resultSet.getString("jadwalBerangkat");
                            
                            tibaLabel.setText("Jadwal Tiba : " + resultSet.getString("jadwalTiba"));
                            jadwalTiba = resultSet.getString("jadwalTiba");
                            
                            hargaLabel.setText("Harga Tiket : " + resultSet.getInt("hargaTiket"));
                            hargaTiket = resultSet.getInt("hargaTiket");
                            
                            asalLabel.setText("Stasiun Asal : " + resultSet.getString("stasiunAsal"));
                            stasiunAsal = resultSet.getString("stasiunAsal");
                            
                            tujuanLabel.setText("Stasiun Tujuan : " + resultSet.getString("stasiunTujuan"));
                            stasiunTujuan = resultSet.getString("stasiunTujuan");
                        }
                    }
                } catch(SQLException e){
                    e.printStackTrace();
                }
            }
        }
        */
    }//GEN-LAST:event_listKAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asalLabel;
    private javax.swing.JLabel berangkatLabel;
    private javax.swing.JLabel etrainText;
    private javax.swing.JLabel gerbongLabel;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JList<String> listKA;
    private javax.swing.JLabel listKAText;
    private javax.swing.JLabel namaKeretaLabel;
    private javax.swing.JLabel tibaLabel;
    private javax.swing.JLabel tujuanLabel;
    // End of variables declaration//GEN-END:variables
}
